FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs \
    npm

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD ./ /code

COPY basesite/package.json /package.json
RUN npm install

CMD /wait.sh db 5432 \
  && /wait.sh blockchain 8545 \
  && cd basesite/ \
  && npx hardhat run scripts/deploy.js --network localhost \
  && cd ../ \
  && python basesite/manage.py collectstatic --noinput \
  && python basesite/manage.py migrate \
  && python basesite/manage.py loaddata data.json \
  && /usr/local/bin/uwsgi --ini /code/basesite/basesite/uwsgi.ini