# Dockerfile-app
# Deploys the NFT smart contract and runs the django API server

FROM python:3.7
WORKDIR /code
ENV PYTHONUNBUFFERED=1
COPY wait.sh /wait.sh
RUN chmod +x /wait.sh

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs \
    npm

COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt
ADD ./ /code

COPY basesite/smart_contract/package.json /basesite/smart_contract/package.json
RUN cd basesite/smart_contract/ && npm install

CMD /wait.sh db 5432 \
  && /wait.sh blockchain 8545 \
  && cd basesite/smart_contract \
  && npx hardhat run scripts/deploy.js --network localhost_docker \
  && cd ../../ \
  && python basesite/manage.py collectstatic --noinput \
  && python basesite/manage.py migrate \
  && python basesite/manage.py loaddata data.json \
  && /usr/local/bin/uwsgi --ini /code/basesite/basesite/uwsgi.ini
