# 1) Node image for building frontend assets
# 2) nginx stage to serve frontend assets

# Stage 1: Node for building frontend assets
FROM node:12 AS builder
WORKDIR /app
COPY basesite/frontend/ .
RUN npm install && npm run build


# Stage 2: Nginx for serving assets
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
# Remove default nginx static assets
RUN rm -rf ./*
COPY --from=builder /app/build .
COPY web.conf /etc/nginx/conf.d/default.conf
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]