FROM nginx:latest

# a command used to build the image:
#RUN apt-get update \
#  && apt-get install -y nginx-module-geoip \
#  && apt-get clean \
#  && rm -rf /var/lib/apt/lists/*

# copy a file into the image when it's built:
#COPY ./timezone /etc/timezone

# command to run when the container starts (default for this image would be fine too):
CMD nginx -g "daemon off; error_log /dev/stdout info;"
