# Generated by Django 3.2.9 on 2021-12-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacecomment',
            old_name='token_id',
            new_name='metadata_id',
        ),
        migrations.RenameField(
            model_name='nft',
            old_name='owner_alias',
            new_name='author_alias',
        ),
        migrations.CreateModel(
            name='MarketPlaceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=200)),
                ('is_followed', models.BooleanField(default=True)),
                ('nft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nft')),
            ],
        ),
    ]
