# Generated by Django 3.2.9 on 2021-11-29 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftmetadata',
            old_name='token_uri',
            new_name='nft_id',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='token_uri',
        ),
        migrations.AddField(
            model_name='nft',
            name='owner_alias',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nft',
            name='token_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nftmetadata',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nftmetadata',
            name='nft_views',
            field=models.IntegerField(default=0),
        ),
    ]
