# Generated by Django 3.2.9 on 2021-12-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211203_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacecomment',
            name='metadata_id',
        ),
        migrations.AddField(
            model_name='marketplacecomment',
            name='nft_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.nft'),
            preserve_default=False,
        ),
    ]
