# Generated by Django 3.2.9 on 2021-12-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211204_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacecomment',
            old_name='nft_id',
            new_name='nft',
        ),
        migrations.RenameField(
            model_name='marketplaceinteraction',
            old_name='nft_id',
            new_name='nft',
        ),
        migrations.RenameField(
            model_name='nftmetadata',
            old_name='nft_id',
            new_name='nft',
        ),
    ]
