# Generated by Django 3.2.9 on 2021-12-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211204_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftmetadata',
            name='nft_comments',
            field=models.IntegerField(default=0),
        ),
    ]
