# Generated by Django 4.0 on 2021-12-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_nftmetadata_nft_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=200)),
                ('is_up_voted', models.BooleanField(default=False)),
                ('is_down_voted', models.BooleanField(default=False)),
                ('nftComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marketplacecomment')),
            ],
        ),
    ]
